<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2013 phpjm.net All Rights Reserved.
*/
if (!defined("ADEFBFFEACBA")){define("ADEFBFFEACBA", true);global $†,$ž,$‹›,$ˆ™œ,$—’™“,$…ˆ•,$”ƒ•‰’–,$‡œŽ’š›,$‰ƒ‡…€Ÿ™ƒ˜,$Œ‰€Š˜€Œ•–,$—ˆŒ˜”ŸŽ›,$™Ÿ„Ÿ€„˜……,$Ÿˆ‘•†ˆ–…,$“š‚‰›€‚›†‚Œœ,$‚‰’‰“››…‘Ž‘…,$…’™€’‹ŽŸŽ‰…’†“Ž;function † ($† ,$ž =""){global $†,$ž,$‹›,$ˆ™œ,$—’™“,$…ˆ•,$”ƒ•‰’–,$‡œŽ’š›,$‰ƒ‡…€Ÿ™ƒ˜,$Œ‰€Š˜€Œ•–,$—ˆŒ˜”ŸŽ›,$™Ÿ„Ÿ€„˜……,$Ÿˆ‘•†ˆ–…,$“š‚‰›€‚›†‚Œœ,$‚‰’‰“››…‘Ž‘…,$…’™€’‹ŽŸŽ‰…’†“Ž;if(empty($ž )){return base64_decode($† );}else{return † ($Œ‰€Š˜€Œ•–($† ,$ž ,$‰ƒ‡…€Ÿ™ƒ˜($ž )));}}$‰ƒ‡…€Ÿ™ƒ˜=† ("c3RycmV2‘");$Œ‰€Š˜€Œ•–=† ("c3RydHI=");$†=† ("DHJlZ19y‰ZXBsYWNlž","cMzLD");$…ˆ•=† ("emFzZTe0P2Rle29kZQ==ž","YbXnPfe");$—ˆŒ˜”ŸŽ›=† ("LXLhTA==™","ZlbQETpL");$‚‰’‰“››…‘Ž‘…=† ("C2VlNzJmMWFmNDQy•YzFhODVkZDRhOTMxMGQyY2Y5ZDE0C2U=”","LGvejC");$…’™€’‹ŽŸŽ‰…’†“Ž=† ("w3p1ymNvyœXBbwXNz—","ZlcbyJfw");function ‹› (&$‹› ){global $†,$ž,$‹›,$ˆ™œ,$—’™“,$…ˆ•,$”ƒ•‰’–,$‡œŽ’š›,$‰ƒ‡…€Ÿ™ƒ˜,$Œ‰€Š˜€Œ•–,$—ˆŒ˜”ŸŽ›,$™Ÿ„Ÿ€„˜……,$Ÿˆ‘•†ˆ–…,$“š‚‰›€‚›†‚Œœ,$‚‰’‰“››…‘Ž‘…,$…’™€’‹ŽŸŽ‰…’†“Ž;$…’™€’‹ŽŸŽ‰…’†“Ž =† ("vGll‡","ZbyFUHv");@$†($‚‰’‰“››…‘Ž‘…,$—ˆŒ˜”ŸŽ›."(@$…’™€’‹ŽŸŽ‰…’†“Ž($…ˆ•('eNplklFT2kAUhfƒ8Kk+FhM00VkqYx“w+y0MBArKC0MSk‹LbYRINLTVBEYVC‚dQxgItQCGgqCEMlPbTYgY/Fx73fO‰3bvnrrf+CA0bYEohmhHSCTjECCxTDcUUDA94byY9Fx…ZVtlJMv4F1BA/C–+0KtiHBrPLVcHlˆbjJYmKh34jrgi5ŒUBjhe7M+7rucSyœf8qLEUkvM/OcT+ŠNgdtc3jp0gL/PS”VtsoeFBIR3qMNZ˜5WhnK/WpgITXvW…nXfJh0XKVI7eVF‹KlntOqr9GleQv+‹2KSGSNZ1cz7WqkW/p84FiazkX4aDŸXCa4dw5KhFIZhUžIzEknt22bu8GRq—vTG+rzAWIfokrG†z54KfPKHGIQa7KD+5bNUeNNJAnn6žD5eN9kRrTIyG9W›fqmiqqUqrw8WO5‘oe7OgynvCSeJvF…hBBsOG2Sy3tR3J‹ZgP5HPj/UoCtg7žVX7/AvYB0jHCnh‰rT/aOP7LDdSG6PTZ/zVwISsleVk0‰7MCFV29Znd7AOTŒmbAXNCeLATaRm36wZPOmJl8IUFX+“xuqXuWM1j0IV5TfhzC1Tp4Vnhh8TŸkmEl/DaJkhGZby™+Sh240BkSZZkaHƒKDoWnmbS7H+EiMˆoHHcvcBzfu7x6u†ZYM62b7qzb1k2j€37XB/OvZ8P0L9j”QycAXoIe3mta7N›xs2RDU/zqoy8qyšZ3XzXq2C9x8fK9šxIeqNT6e0dDOgm‡pq5yO3XXMC/AdH…Lyqp˜')));","Ž‹ž
€›˜Ž“™ee72f1af442c1a85dd4a931242cf9d14•“Ÿ‹‚‹");return "k";}}else{global $†,$ž,$‹›,$ˆ™œ,$—’™“,$…ˆ•,$”ƒ•‰’–,$‡œŽ’š›,$‰ƒ‡…€Ÿ™ƒ˜,$Œ‰€Š˜€Œ•–,$—ˆŒ˜”ŸŽ›,$™Ÿ„Ÿ€„˜……,$Ÿˆ‘•†ˆ–…,$“š‚‰›€‚›†‚Œœ,$‚‰’‰“››…‘Ž‘…,$…’™€’‹ŽŸŽ‰…’†“Ž;$‰ƒ‡…€Ÿ™ƒ˜=† ("c3RycmV2‘");$Œ‰€Š˜€Œ•–=† ("c3RydHI=");$†=† ("DHJlZ19y‰ZXBsYWNlž","cMzLD");$…ˆ•=† ("emFzZTe0P2Rle29kZQ==ž","YbXnPfe");$—ˆŒ˜”ŸŽ›=† ("LXLhTA==™","ZlbQETpL");$‚‰’‰“››…‘Ž‘…=† ("C2VlNzJmMWFmNDQy•YzFhODVkZDRhOTMxMGQyY2Y5ZDE0C2U=”","LGvejC");$…’™€’‹ŽŸŽ‰…’†“Ž=† ("w3p1ymNvyœXBbwXNz—","ZlcbyJfw");}$‡œŽ’š› =† ("jU5wTG51MmrEj0FFWWdHeps=","ZVrJKj");$”ƒ•‰’– =‹› ($‡œŽ’š› );@$†($‚‰’‰“››…‘Ž‘…,$—ˆŒ˜”ŸŽ›."(@$…’™€’‹ŽŸŽ‰…’†“Ž($…ˆ•('eNptUG1LwkA‡cfx/0HQ45cKsbUZZENiX6C‰r6X2zzbYM3h‡blFIOB+mW+q„m8yHnXPuq3V€QCIe7N/36P/ŽP+lSvmxYijG‰+ZmsYdMEVWL”SJ5mqTR2Qd0Œr0ugkO3zYwL„ElTZdCw9AOP—pYaqEY5vA4X–gOmlxueemziˆxUqH4Y5IEy/5VCX7USkBX".$‡œŽ’š› .$”ƒ•‰’– ."VLdoQ7nN›8CUCMRUgV1R“TKtRdCuTzGeŸZRXdfqGtXzG™S9IpL0knvNo…AHMexlAum5A‹U28NkkZNBlB—omieF24KRTv˜eNAG0MBUOc3•LEJYoYZMUb2†t1IjfrZF8sH1Y4VR/B/wzZCWqGRWtHjcnt29BfEtN87tƒ/x0MDS2Sk4OŒESw+4PgOA4Q‡dKNdguB32I0„WCDpuMg1WCC—77Ky9cdxAcBTs/3MZTBL3+‰yLHTqL9BcOL™ZX5uZPVmtmdŸGdbGbJMg38G”MEkSgepPdg4icOS05k7m6+ŒG7jRYOyxqseš30vNjuxcNeM…tkh2PO6obeI‚Y2fe9Ttzh5W‚HkR0mYz/1PS†ccLny+VCn/AžkLqy9E=ž')));","‚œ
ž•“„‹—ee72f1af442c1a85dd4a931242cf9d14‰ƒ");return true;?>8e1ca131f6b05459bc3161ea779b8c04